name: Tag sync
on:
  push:
    branch: master

env:
  APP_ID: 174141
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install depends for load scripts
        run: |
          npm install tag-syncer@1.2.0
          npm install @octokit/rest
      - name: Get token using github-script
        id: get-token
        uses: actions/github-script@v6
        env:
          base: ${{ github.event.before }}
          head: ${{ github.event.after }}
        with:
          script: |
            const { Tag, yamlLoad, GetToken } = require('tag-syncer');
            const { Octokit } = require("@octokit/rest");
            const { APP_ID, APP_PRIVATE_KEY, base, head } = process.env;
            const path = require('path')
            const app = {
              APP_ID,
              APP_PRIVATE_KEY
            };

            const appOctokit = new Octokit();
            const changedFiles = await appOctokit.rest.repos.compareCommits({
              ...context.repo,
              base,
              head
            });
            const files = changedFiles.data.files.map(ele => ele.filename);
            console.log(files)
            const tags = files.filter(item => {
                if (!item.startsWith('tags')) {
                    return false;
                }
                return 'json' === item.split('.')[item.split('.').length -1];
            })
            for (const file of tags) {
              const root = yamlLoad(file);
              if (root === null) {
                continue;
              }
              const repo = {
                owner: context.payload.organization.login,
                repo: path.basename(path.resolve(file), '.json')
              };
              const octokit = new Octokit({
                auth: await GetToken(app, repo)
              });
              const { sha, tag, author, email, description } = yamlLoad(file).version;
              await Tag(octokit, repo.owner, repo.repo, sha, tag, description, author, email);
            }
